name: Deploy to cPanel

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cPanel Git pull
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CPANEL_SSH_HOST }}
          username: ${{ secrets.CPANEL_SSH_USER }}
          password: ${{ secrets.CPANEL_SSH_PASSWORD }}
          script: |
            cd ${{ secrets.CPANEL_REPO_PATH }}
            git pull origin prod
